---
title: testing survey archetype
author: Pinaki Bhattacharyya
date: '2021-05-25'
slug: testing-survey-archetype
categories:
  - Demo
tags:
  - Academic
subtitle: ''
summary: ''
authors: []
lastmod: '2021-05-25T02:05:51+05:30'
featured: no
disable_jquery: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

**doi:** https://doi.org/10.1103/PhysRevLett.125.140604https://
**Abstract:**
This Letter presents a neural estimator for entropy production (NEEP), that estimates entropy production (EP) from trajectories of relevant variables without detailed information on the system dynamics. For steady state, we rigorously proved that the estimator, which can be built up from different choices of deep neural networks, provides stochastic EP by optimizing the objective function proposed here. We verify the NEEP with the stochastic processes of the bead spring and discrete flashing ratchet models and also demonstrate that our method is applicable to high-dimensional data and can provide coarse-grained EP for Markov systems with unobservable states.

# Summary Notes
My Own Notes and key takeaways. 

# Further Reading
Or better bibtex type citations?
* [Reference 1 title]()
* [Reference 2 title]()
