---
title: Testing surver archetypes 2
author: Pinaki Bhattacharyya
date: '2021-05-25'
slug: testing-surver-archetypes-2
categories:
  - Demo
tags:
  - Academic
subtitle: '[http://localhost:4321/survey/testing-surver-archetypes-2/](http://localhost:4321/survey/testing-surver-archetypes-2/)'
summary: 'This Letter presents a neural estimator for entropy production, or NEEP, that estimates entropy production (EP) from trajectories of relevant variables without detailed information on the system dynamics. For steady state, we rigorously prove that the estimator, which can be built up from different choices of deep neural networks, provides stochastic EP by optimizing the objective function proposed here. We verify the NEEP with the stochastic processes of the bead-spring and discrete flashing ratchet models, and also demonstrate that our method is applicable to high-dimensional data and can provide coarse-grained EP for Markov systems with unobservable states'
authors: [Pinaki Bhattacharyya]
lastmod: '2021-05-25T02:40:48+05:30'
featured: yes
disable_jquery: no
image:
  caption: 'neural networks'
  focal_point: ''
  preview_only: no
projects: []
reading_time: true  # Show estimated reading time?
share: true  # Show social sharing links?
profile: true  # Show author profile?
commentable: false  # Allow visitors to comment? Supported by the Page, Post, and Docs content types.
---

**doi:** http://localhost:4321/survey/testing-surver-archetypes-2/

**Abstract:**
We developed the neural estimator for entropy production (NEEP), a novel type of estimator that evaluates entropy production from the trajectories of system variables by deep learning. In the macroscopic world, entropy never decreases as time moves forward; for instance, spilled water will not spontaneously jump back into its cup. However, entropy can in fact transiently decrease in small systems due to environmental fluctuations. Physicists have found that such an entropy difference, called entropy production (EP), can be measured by estimating the probability that a time-reversed trajectory, which is like playing a recorded video from an experiment backward, will be observed. Various EP estimators based on this method have been developed, but the required trajectory data needs to first be divided into discrete microstates. In contrast to these conventional methods, NEEP does not require such detailed information to estimate the probability of time-reversed trajectories, and further, NEEP can efficiently learn EP from data even in high-dimensional space. We additionally verified that our approach is even applicable to time-series data with unobservable variables. We expect NEEP to be beneficial in applications to intricately organized systems where numerous variables are entangled and hidden, such as biological systems, active matter, and others, for a deeper look into their complex dynamics.

---
# Summary Notes


# Further Reading
